import type { CatalogDTO, ModifierGroupDTO, OrderRecordDTO, ProductDTO, ShiftDTO } from "./types";

export const DEFAULT_MODIFIER_GROUPS: ModifierGroupDTO[] = [
  {
    id: "mg-temp",
    code: "TEMPERATURE",
    name: "Ice Level",
    selectionType: "SINGLE",
    isRequired: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: "opt-reg-ice", code: "ICE_REGULAR", name: "Regular Ice", priceDelta: 0, isDefault: true },
      { id: "opt-less-ice", code: "ICE_LESS", name: "Less Ice", priceDelta: 0, isDefault: false },
    ],
  },
  {
    id: "mg-size",
    code: "SIZE",
    name: "Cup Size",
    selectionType: "SINGLE",
    isRequired: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: "opt-regular", code: "SIZE_REGULAR", name: "Regular (12oz)", priceDelta: 0, isDefault: true },
    ],
  },
  {
    id: "mg-sweet",
    code: "SWEETNESS",
    name: "Sweetness Level",
    selectionType: "SINGLE",
    isRequired: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      { id: "opt-sweet-100", code: "SWEET_100", name: "Normal (100%)", priceDelta: 0, isDefault: true },
      { id: "opt-sweet-50", code: "SWEET_50", name: "Less Sweet (50%)", priceDelta: 0, isDefault: false },
      { id: "opt-sweet-0", code: "SWEET_0", name: "Unsweetened (0%)", priceDelta: 0, isDefault: false },
    ],
  },
  {
    id: "mg-milk",
    code: "MILK",
    name: "Milk Selection",
    selectionType: "SINGLE",
    isRequired: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      { id: "opt-milk-fresh", code: "MILK_FRESH", name: "Fresh Dairy Milk", priceDelta: 0, isDefault: true },
    ],
  },
];

export const DEFAULT_CATALOG: CatalogDTO = {
  categories: [
    { id: "cat-sig", name: "Signature Coffee", slug: "signature", icon: "Sparkles" },
    { id: "cat-esp", name: "Espresso Based", slug: "espresso", icon: "Coffee" },
    { id: "cat-flt", name: "Manual Brew / Filter", slug: "filter", icon: "FlaskConical" },
    { id: "cat-non", name: "Non-Coffee Specials", slug: "non-coffee", icon: "Leaf" },
    { id: "cat-pst", name: "Pastry & Bakery", slug: "pastry", icon: "Croissant" },
  ],
  products: [],
};

export const DEFAULT_SHIFT: ShiftDTO = {
  id: "shift-live-01",
  cashierName: "Alex Rivera",
  openedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  openingCash: 300000,
  status: "OPEN",
};

export const INITIAL_ORDERS: OrderRecordDTO[] = [
  {
    id: "ord-101",
    orderNumber: "DCC-261003-0012",
    queueNumber: 12,
    orderType: "TAKEAWAY",
    customerName: "Sarah Jenkins",
    tableNumber: null,
    status: "PROCESSING", // In Preparation / Brewing!
    subtotal: 56000,
    discountType: "NONE",
    discountValue: 0,
    discountCode: null,
    discountAmount: 0,
    taxRate: 10,
    taxAmount: 5600,
    total: 61600,
    shiftId: "shift-live-01",
    cashierName: "Alex Rivera",
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(), // 4 mins ago
    items: [
      {
        id: "item-101-1",
        productId: "prod-sig-1",
        productName: "Caminos Aren Palm Latte",
        categoryName: "Signature Coffee",
        isBeverage: true,
        basePrice: 28000,
        unitPrice: 38000,
        quantity: 1,
        lineTotal: 38000,
        note: "Extra cold, write 'Sarah' with smiley face",
        modifiers: [
          { groupCode: "TEMPERATURE", groupName: "Temperature", optionCode: "TEMP_ICED", optionName: "Iced", priceDelta: 0 },
          { groupCode: "SIZE", groupName: "Cup Size", optionCode: "SIZE_REGULAR", optionName: "Regular (12oz)", priceDelta: 0 },
          { groupCode: "MILK", groupName: "Milk Selection", optionCode: "MILK_OAT", optionName: "Oat Milk", priceDelta: 10000 },
          { groupCode: "SWEETNESS", groupName: "Sweetness Level", optionCode: "SWEET_50", optionName: "Less Sweet (50%)", priceDelta: 0 },
        ],
      },
      {
        id: "item-101-2",
        productId: "prod-pst-1",
        productName: "Golden Butter Croissant",
        categoryName: "Pastry & Bakery",
        isBeverage: false,
        basePrice: 25000,
        unitPrice: 25000,
        quantity: 1,
        lineTotal: 25000,
        note: "Warm up please",
        modifiers: [],
      },
    ],
    payment: {
      method: "QRIS",
      amount: 61600,
      tendered: 61600,
      change: 0,
      qrisMode: "DYNAMIC",
      reference: "QRIS-BCA-984321",
    },
  },
  {
    id: "ord-102",
    orderNumber: "DCC-261003-0013",
    queueNumber: 13,
    orderType: "DINE_IN",
    customerName: "David Kim",
    tableNumber: "Table 04",
    status: "PROCESSING", // In Preparation / Brewing!
    subtotal: 76000,
    discountType: "PERCENT",
    discountValue: 10,
    discountCode: "DUVAL10",
    discountAmount: 7600,
    taxRate: 10,
    taxAmount: 6840,
    total: 75240,
    shiftId: "shift-live-01",
    cashierName: "Alex Rivera",
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2 mins ago
    items: [
      {
        id: "item-102-1",
        productId: "prod-flt-1",
        productName: "Single Origin V60 Pour Over",
        categoryName: "Manual Brew / Filter",
        isBeverage: true,
        basePrice: 35000,
        unitPrice: 35000,
        quantity: 1,
        lineTotal: 35000,
        note: "Ethiopia Yirgacheffe beans",
        modifiers: [
          { groupCode: "TEMPERATURE", groupName: "Temperature", optionCode: "TEMP_HOT", optionName: "Hot", priceDelta: 0 },
          { groupCode: "SIZE", groupName: "Cup Size", optionCode: "SIZE_REGULAR", optionName: "Regular (12oz)", priceDelta: 0 },
        ],
      },
      {
        id: "item-102-2",
        productId: "prod-sig-2",
        productName: "Creamy Duval Vanilla",
        categoryName: "Signature Coffee",
        isBeverage: true,
        basePrice: 32000,
        unitPrice: 41000,
        quantity: 1,
        lineTotal: 41000,
        note: null,
        modifiers: [
          { groupCode: "TEMPERATURE", groupName: "Temperature", optionCode: "TEMP_ICED", optionName: "Iced", priceDelta: 0 },
          { groupCode: "SIZE", groupName: "Cup Size", optionCode: "SIZE_REGULAR", optionName: "Regular (12oz)", priceDelta: 0 },
          { groupCode: "ADDON", groupName: "Add-ons & Extras", optionCode: "ADDON_EXTRA_SHOT", optionName: "Extra Espresso Shot", priceDelta: 5000 },
          { groupCode: "SIZE", groupName: "Cup Size", optionCode: "SIZE_LARGE", optionName: "Large (16oz)", priceDelta: 6000 },
        ],
      },
    ],
    payment: {
      method: "CASH",
      amount: 75240,
      tendered: 100000,
      change: 24760,
    },
  },
  {
    id: "ord-100",
    orderNumber: "DCC-261003-0011",
    queueNumber: 11,
    orderType: "TAKEAWAY",
    customerName: "Michael Evans",
    tableNumber: null,
    status: "COMPLETED", // Ready / Handed over!
    subtotal: 28000,
    discountType: "NONE",
    discountValue: 0,
    discountCode: null,
    discountAmount: 0,
    taxRate: 10,
    taxAmount: 2800,
    total: 30800,
    shiftId: "shift-live-01",
    cashierName: "Alex Rivera",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    items: [
      {
        id: "item-100-1",
        productId: "prod-esp-2",
        productName: "Silky Caffe Latte",
        categoryName: "Espresso Based",
        isBeverage: true,
        basePrice: 28000,
        unitPrice: 28000,
        quantity: 1,
        lineTotal: 28000,
        note: null,
        modifiers: [
          { groupCode: "TEMPERATURE", groupName: "Temperature", optionCode: "TEMP_HOT", optionName: "Hot", priceDelta: 0 },
          { groupCode: "SIZE", groupName: "Cup Size", optionCode: "SIZE_REGULAR", optionName: "Regular (12oz)", priceDelta: 0 },
        ],
      },
    ],
    payment: {
      method: "DEBIT_EDC",
      amount: 30800,
      tendered: 30800,
      change: 0,
      reference: "EDC-MANDIRI-440219",
    },
  },
];
